pragma solidity ^0.5.0;

contract SampleContract {
    User[] public allowed;

    // Data parameter is only a sample
    struct User {
    	address Addr;
	bytes32 Data;
    }
    
    function verifyMock(uint[] calldata _input, bytes32 _proof) internal {
    
    }

    function addAllowed(
    	// the _proof will be a zkproof generated by snarkjs,
	// being of Proof type. Temporary is a bytes32
    	address _addr, bytes32 _data, uint[] calldata _input, bytes32 _proof
    ) external {
    	// verification here
	verifyMock(_input, _proof);

        allowed.push(User(_addr, _data));
    }
}
